[".git-prompt.sh"]
type = "file"
url = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
refreshPeriod = "168h"

[".local/bin/fzf-tmux"]
type = "file"
url = "https://raw.githubusercontent.com/junegunn/fzf/master/bin/fzf-tmux"
executable = true
refreshPeriod = "168h"

[".local/bin/mo"]
type = "archive-file"
url = "https://github.com/k1LoW/mo/releases/download/v1.6.6/mo_v1.6.6_linux_amd64.tar.gz"
path = "mo"
executable = true
refreshPeriod = "168h"

[".config/tmux/plugins/tmux-power"]
type = "git-repo"
url = "https://github.com/wfxr/tmux-power.git"
refreshPeriod = "168h"

[".local/share/sourcegit/sourcegit.AppImage"]
type = "file"
url = "https://github.com/sourcegit-scm/sourcegit/releases/download/v2026.17/sourcegit-2026.17.linux.arm64.AppImage"
executable = true
refreshPeriod = "168h"
