[tools]
# mise
usage = "latest"

# util
github-cli = "latest"
chezmoi = "latest"
fzf = "latest"
fd = "latest"
eza = { version = "latest", repo = "asdf:mise-plugins/mise-eza" }
lazygit = "latest"
delta = { version = "latest", repo = "andweeb/asdf-delta" }
zoxide = { version = "latest", repo = "asdf:nyrst/asdf-zoxide" }
bat = { version = "latest", repo = "asdf:https://gitlab.com/wt0f/asdf-bat" }
