[tools]
# mise
usage = "latest"

# util
github-cli = "latest"
chezmoi = "latest"
fzf = "latest"
fd = "latest"
eza = "0.23.4"
lazygit = "latest"
delta = { version = "latest", repo = "andweeb/asdf-delta" }
