# エディターの補完を設定スキーマに合わせて取得
"$schema" = 'https://starship.rs/config-schema.json'

# プロンプト前の空行を無効化
add_newline = false

# ====== Powerline風 1行プロンプト (全セグメント左寄せ) ======
format = """[ $directory ](bg:#00abab fg:#262626)([](fg:#00abab bg:#afaf00)[ $git_branch$git_status ](bg:#afaf00 fg:#262626)[](fg:#afaf00)) $character"""


# ディレクトリ
[directory]
truncation_length = 3
truncation_symbol = ".../"
truncate_to_repo = false
format = "$path$read_only"
read_only = " "

# Git ブランチ
[git_branch]
symbol = " "
format = "$symbol$branch"

# Git 状態
[git_status]
format = '$all_status$ahead_behind'

# プロンプト文字
[character]
success_symbol = "[ ❯](bold green)"
error_symbol = "[ ❯](bold red)"
